### ISSUE TITLE
Chuck's outside 0.5 checklist

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#1302]
- [ ] Figure out how CEDAR will be integrated with existing tools.
- [ ] Talk with Alex and get a plan that will move directory schemas forward.
- [ ] Make an outline for FAIR assessment.

**Comment by mccalluc** [comment]
- Still no solid advances on directory schema.
- Talking with Nils tomorrow about CEDAR
- Started on FAIR, but scope could be clearer.

**Comment by mccalluc** [comment]
- CEDAR will not move forward.
- Alex has delivered some directory schemas.
- [FAIR assessment](https://docs.google.com/document/d/1fc3r3JGiXmg3If7aYV_K5BQTVa-yY0U3tAggBknkw_Q/edit#) is done. Not pretty.

Closing.
