### ISSUE TITLE
Tracker Task for Ilan

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1465]
Not sure how to mark whether the first one is complete or not but the other two should be pretty clearly done:
- [x] Viv 3D work: https://docs.google.com/document/d/1swidpzUFDjSZOjK98XW-r-QTVW9D8klgZ-3DYWUGA6c/edit#
- [x] Zarr-for-Anndata + Vitessce: https://github.com/vitessce/vitessce-python/pull/39 + https://github.com/theislab/anndata/issues/491
- [x] Integrate latest Viv into Vitessce: https://github.com/hms-dbmi/viv/blob/master/CHANGELOG.md#in-progress (`transparentColorProp` + scaling fix + [geotiff fix](https://github.com/hms-dbmi/viv/pull/354))

**Comment by ilan-gold** [comment]
I made considerable progress on the first one and the last two are done.
