### ISSUE TITLE
Tracker Task for Sprint 13

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/portal-ui#1588]
Small Issues in Histograms/Violin Plots (Vitessce):
- [x] https://github.com/vitessce/vitessce/issues/851
- [x] https://github.com/vitessce/vitessce/issues/852

Improve Initial Load times (Vitessce):
- [ ] https://github.com/hubmapconsortium/portal-ui/issues/1516
- [ ] Finish up https://github.com/vitessce/vitessce/pull/849 to resolve the above

Look in the time needed for selection on large cell x gene datasets (Vitessce):
- [x] https://github.com/vitessce/vitessce/issues/854
- [x] https://github.com/vitessce/vitessce/issues/871

**Comment by ilan-gold** [comment]
Closing this out.  The imaging stuff was always a stretch in case I had time and is not a priority.
