### ISSUE TITLE
Tracker issue for provenance redesign

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#2017]
- [ ] Complete [proposal/task lists document](https://docs.google.com/document/d/1jETxU6qpovN-z51KBNpGDI3ensEc2yif6lGGMs1qqvY/edit#) for receiving user feedback on provenance
- [ ] Send out survey to relevant target users
- [ ] Analyze user feedback to determine changes to provenance graph

**Comment by tsliaw** [comment]
Update: Scenarios have been gathered from in the [proposal/task lists document ](https://docs.google.com/document/d/1jETxU6qpovN-z51KBNpGDI3ensEc2yif6lGGMs1qqvY/edit#) and I'll put that in the upcoming UI meeting to discuss to update the survey with.
